# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tasks.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'tasks.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btasks.proto\x12\x05tasks\"\x07\n\x05\x45mpty\"5\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"&\n\x08TaskList\x12\x1a\n\x05tasks\x18\x01 \x03(\x0b\x32\x0b.tasks.Task28\n\x0bTaskService\x12)\n\x08GetTasks\x12\x0c.tasks.Empty\x1a\x0f.tasks.TaskListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tasks_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=22
  _globals['_EMPTY']._serialized_end=29
  _globals['_TASK']._serialized_start=31
  _globals['_TASK']._serialized_end=84
  _globals['_TASKLIST']._serialized_start=86
  _globals['_TASKLIST']._serialized_end=124
  _globals['_TASKSERVICE']._serialized_start=126
  _globals['_TASKSERVICE']._serialized_end=182
# @@protoc_insertion_point(module_scope)
